name: Build Navic

on:
  push:
    paths:
      - composeApp/**
      - gradle/**
      - iosApp/**
      - subsonic/**
      - build.gradle.kts
      - settings.gradle.kts
  pull_request:
    paths:
      - composeApp/**
      - gradle/**
      - iosApp/**
      - subsonic/**
      - build.gradle.kts
      - settings.gradle.kts
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-apk:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build with Gradle
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          SIGNING_STORE_FILE: ${{ github.workspace }}/release.keystore
          RELEASE: true
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 -d > release.keystore
          ./gradlew :composeApp:packageRelease --stacktrace
          rm release.keystore

      - name: Upload APK artifact
        uses: actions/upload-artifact@v6
        with:
          name: navic-release-android
          path: composeApp/build/outputs/apk/release/*.apk
  build-ipa:
    name: Build iOS IPA
    runs-on: macos-26
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Cache konan
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle.kts', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Build IPA
        run: |
          xcodebuild archive \
            -project iosApp/iosApp.xcodeproj \
            -scheme iosApp \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "iosApp.xcarchive" \
            CODE_SIGN_ENTITLEMENTS="iosApp/entitlements.xml" \
            CODE_SIGN_IDENTITY="-" \
            CODE_SIGN_STYLE=Manual \
            AD_HOC_CODE_SIGNING_ALLOWED=YES

          mkdir -p Payload

          APP_PATH=$(find "iosApp.xcarchive/Products/Applications" -name "*.app" | head -n 1)
          cp -r "$APP_PATH" Payload/

          zip -r "Navic.ipa" Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: navic-release-ios
          path: Navic.ipa
          compression-level: 0
